apiVersion: v1
kind: Service
metadata:
  name: encrypted-chat-backend
spec:
  selector:
    app: encrypted-chat-backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: encrypted-chat-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: encrypted-chat-backend
  template:
    metadata:
      labels:
        app: encrypted-chat-backend
    spec:
      containers:
      - name: encrypted-chat-backend
        image: encrypted-chat-backend
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URI
          value: TO_FILL
        - name: PORT
          value: "8000"
        - name: JWT_SECRET
          value: TO_FILL
        - name: CLIENT_URI
          value: http://encrypted-chat-frontend:3000
        imagePullPolicy: Never
